# Site settings
title: RTEMS , GSoC 2018
email: vijaykumar9597@gmail.com
description: >
  Improve Coverage Analysis Toolset

baseurl: "/rtems_gsoc18" # the subpath of your site, e.g. /blog/
url: https://thelunatic.github.io/rtems_gsoc18 # the base hostname & protocol for your site
git_address: https://github.com/thelunatic/rtems-tools
git_edit_address: https://github.com/thelunatic/rtems-tools

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: India
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

- scope:
    path: _codes
    type: codes
  values:
    layout: docs
    sectionid: codes
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:title/
    output: true
  codes:
    permalink: /:collection/:path/
    output: true
 
